adb shell pm install-existing --user 0 com.android.mms.service
adb shell pm install-existing --user 0 com.coloros.athena
adb shell pm install-existing --user 0 com.coloros.calculator
adb shell pm install-existing --user 0 com.coloros.encryption
adb shell pm install-existing --user 0 com.coloros.focusmode
adb shell pm install-existing --user 0 com.coloros.gamespace
adb shell pm install-existing --user 0 com.coloros.providers.downloads.ui
adb shell pm install-existing --user 0 com.coloros.sau
adb shell pm install-existing --user 0 com.coloros.translate.engine
adb shell pm install-existing --user 0 com.google.android.accessibility.soundamplifier
adb shell pm install-existing --user 0 com.google.android.apps.nbu.paisa.user
adb shell pm install-existing --user 0 com.google.android.configupdater
adb shell pm install-existing --user 0 com.google.android.contacts
adb shell pm install-existing --user 0 com.google.android.ims
adb shell pm install-existing --user 0 com.google.android.inputmethod.latin
adb shell pm install-existing --user 0 com.google.android.syncadapters.contacts
adb shell pm install-existing --user 0 com.heytap.openid
adb shell pm install-existing --user 0 com.nearme.romupdate
adb shell pm install-existing --user 0 com.oplus.romupdate
adb shell pm install-existing --user 0 com.oplus.sau
adb shell pm install-existing --user 0 com.opos.cs
adb shell pm install-existing --user 0 com.oppoex.afterservice
adb shell pm install-existing --user 0 com.qti.snapdragon.qdcm_ff
adb shell pm install-existing --user 0 com.google.android.dialer
adb shell pm install-existing --user 0 com.realme.securitycheck
adb shell pm install-existing --user 0 com.qti.xdivert
adb shell pm install-existing --user 0 com.google.android.apps.messaging
adb shell pm install-existing --user 0 com.google.android.apps.maps
adb shell pm install-existing --user 0 com.coloros.soundrecorder
adb shell pm install-existing --user 0 com.google.android.googlequicksearchbox
adb shell pm install-existing --user 0 com.google.android.ext.shared
adb shell pm install-existing --user 0 com.android.bookmarkprovider
adb shell pm install-existing --user 0 com.android.carrierdefaultapp
adb shell pm install-existing --user 0 com.android.cts.ctsshimcom.android.ons
adb shell pm install-existing --user 0 com.android.sharedstoragebackup
adb shell pm install-existing --user 0 com.android.simappdialog
adb shell pm install-existing --user 0 com.android.stk
adb shell pm install-existing --user 0 com.android.wallpaperbackup
adb shell pm install-existing --user 0 com.google.android.tts
adb shell pm install-existing --user 0 com.oplus.atlas
adb shell pm install-existing --user 0 com.oplus.commercial
adb shell pm install-existing --user 0 com.oplus.melody
adb shell pm install-existing --user 0 com.oplus.nhs
adb shell pm install-existing --user 0 com.oplus.sos
adb shell pm install-existing --user 0 com.oplus.subsys
adb shell pm install-existing --user 0 com.qualcomm.qti.lpa
adb shell pm install-existing --user 0 com.realme.movieshot
adb shell pm install-existing --user 0 com.ses.entitlement.o2

set /p exitkey= "Press any key to continue..."